# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

uses: dawidd6/action-send-mail@v3
  with:
    # Required mail server address:
    server_address: smtp.gmail.com
    # Required mail server port:
    server_port: 465
    # Optional (recommended): mail server username:
    username: 'Mayke Ken'
    # Optional (recommended) mail server password:
    password: 'Codebase1@1'
    # Required mail subject:
    subject: Github Actions job result
    # Required recipients' addresses:
    to: devmayke@gmail.com,incogntaor@gmail.com
    # Required sender full name (address can be skipped):
    from: Luke Skywalker # <devmayke@gmail.com>
